name = "prisma-cf-workers"
type = "webpack"
webpack_config = "webpack.config.js"
route = ''
zone_id = ''
workers_dev = true
compatibility_date = "2022-01-17"
main= 'src/index.ts'
node_compat = true

[vars]
DATABASE_URL="prisma://aws-eu-central-1.prisma-data.com/?api_key=eX1VVxUNepeyokPKEyxhE6FaAHIFp3LLpxW3L-ePq9dPPBkhvOEvhsq5RDv39qLi"

